import type { ConditionsData } from '../../types/conditions'

const mockConditionsData: ConditionsData = {
  fishingScore: 72,
  scoreLabel: 'Great day to fish',
  bestWindow: { start: '2:00 PM', end: '5:00 PM', score: 85 },
  wind: { speed: 8, gusts: 12, direction: 225, directionLabel: 'SW', unit: 'mph' },
  windHourly: [
    { hour: 6, speed: 5, gusts: 8, direction: 200, directionLabel: 'SSW' },
    { hour: 7, speed: 6, gusts: 9, direction: 205, directionLabel: 'SSW' },
    { hour: 8, speed: 7, gusts: 10, direction: 210, directionLabel: 'SSW' },
    { hour: 9, speed: 8, gusts: 12, direction: 215, directionLabel: 'SW' },
    { hour: 10, speed: 9, gusts: 13, direction: 220, directionLabel: 'SW' },
    { hour: 11, speed: 10, gusts: 15, direction: 225, directionLabel: 'SW' },
    { hour: 12, speed: 11, gusts: 16, direction: 225, directionLabel: 'SW' },
    { hour: 13, speed: 12, gusts: 18, direction: 230, directionLabel: 'SW' },
    { hour: 14, speed: 13, gusts: 19, direction: 230, directionLabel: 'SW' },
    { hour: 15, speed: 12, gusts: 17, direction: 225, directionLabel: 'SW' },
    { hour: 16, speed: 10, gusts: 15, direction: 220, directionLabel: 'SW' },
    { hour: 17, speed: 8, gusts: 12, direction: 215, directionLabel: 'SSW' },
  ],
  airHourly: [
    { hour: 6, temp: 54, rainChance: 5, cloudCover: 60 },
    { hour: 7, temp: 55, rainChance: 5, cloudCover: 55 },
    { hour: 8, temp: 57, rainChance: 8, cloudCover: 50 },
    { hour: 9, temp: 59, rainChance: 10, cloudCover: 45 },
    { hour: 10, temp: 61, rainChance: 10, cloudCover: 40 },
    { hour: 11, temp: 63, rainChance: 12, cloudCover: 35 },
    { hour: 12, temp: 64, rainChance: 15, cloudCover: 40 },
    { hour: 13, temp: 65, rainChance: 15, cloudCover: 45 },
    { hour: 14, temp: 64, rainChance: 18, cloudCover: 50 },
    { hour: 15, temp: 62, rainChance: 12, cloudCover: 55 },
    { hour: 16, temp: 60, rainChance: 8, cloudCover: 60 },
    { hour: 17, temp: 58, rainChance: 5, cloudCover: 60 },
  ],
  swellHourly: [
    { hour: 6, height: 2.1, period: 9, directionLabel: 'W' },
    { hour: 7, height: 2.3, period: 9, directionLabel: 'W' },
    { hour: 8, height: 2.4, period: 10, directionLabel: 'WNW' },
    { hour: 9, height: 2.6, period: 10, directionLabel: 'WNW' },
    { hour: 10, height: 2.8, period: 11, directionLabel: 'NW' },
    { hour: 11, height: 3.0, period: 11, directionLabel: 'NW' },
    { hour: 12, height: 3.1, period: 12, directionLabel: 'NW' },
    { hour: 13, height: 3.0, period: 11, directionLabel: 'NW' },
    { hour: 14, height: 2.8, period: 11, directionLabel: 'WNW' },
    { hour: 15, height: 2.6, period: 10, directionLabel: 'WNW' },
    { hour: 16, height: 2.4, period: 10, directionLabel: 'W' },
    { hour: 17, height: 2.2, period: 9, directionLabel: 'W' },
  ],
  tide: {
    current: { height: 3.2, rising: true, unit: 'ft' },
    next: { type: 'high', time: '3:42 PM', height: 5.1 },
    events: [
      { type: 'low', time: '9:15 AM', height: 0.4 },
      { type: 'high', time: '3:42 PM', height: 5.1 },
    ],
    hourlyCurve: [2.1, 1.8, 1.5, 1.2, 1.0, 1.1, 1.4, 1.9, 2.5, 3.1, 3.6, 4.0, 4.3, 4.5, 4.6, 4.5, 4.2, 3.7, 3.1, 2.5, 2.0, 1.7, 1.6, 1.8],
    phase: 'incoming',
  },
  water: { temp: 58, unit: '°F', estimated: false },
  air: { temp: 62, high: 67, low: 55, humidity: 72, unit: '°F' },
  pressure: { value: 30.05, trend: 'falling', rate: 'slow', unit: 'inHg', readings: [30.18, 30.05] },
  swell: null,
  sky: { condition: 'Overcast', rainChance: 10, icon: 'overcast' },
  sun: { sunrise: '6:08 AM', sunset: '7:52 PM', goldenHourMorning: '6:38 AM', goldenHourEvening: '7:22 PM' },
  moon: {
    phase: 'Waxing Gibbous',
    illumination: 72,
    majorPeriods: [{ start: '2:00 PM', end: '3:00 PM' }],
    minorPeriods: [{ start: '8:00 AM', end: '9:00 AM' }],
  },
  hourlyScores: [],
  tidePhasesByHour: {},
  scoreBreakdown: { pressure: 25, solunar: 14, tide: 15, wind: 13, waterTemp: 8, sky: 10 },
}

export default mockConditionsData
